// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TicketEase.Service.TicketPurchase.DbContexts;

#nullable disable

namespace TicketEase.Service.TicketPurchase.Migrations
{
    [DbContext(typeof(TicketPurchaseDbContext))]
    [Migration("20250128004823_addfunctionsimilar")]
    partial class addfunctionsimilar
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TicketEase.Service.TicketPurchase.Entities.Function", b =>
                {
                    b.Property<Guid>("FunctionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FunctionDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MovieId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("FunctionId");

                    b.ToTable("Functions");

                    b.HasData(
                        new
                        {
                            FunctionId = new Guid("2a943434-f25e-4233-97b8-0135de632951"),
                            FunctionDate = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = new Guid("7a573bf8-d473-4291-b221-b39b7ca415c9"),
                            Price = 50.00m
                        },
                        new
                        {
                            FunctionId = new Guid("44b2a7b7-f0ff-4a74-8bbf-856c19abfdb9"),
                            FunctionDate = new DateTime(2025, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = new Guid("d12f5f9e-05a3-4742-8ecf-174c4ae57527"),
                            Price = 65.00m
                        },
                        new
                        {
                            FunctionId = new Guid("3b0d79ff-a7e0-4d40-b594-44a49f380634"),
                            FunctionDate = new DateTime(2025, 1, 25, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = new Guid("7a573bf8-d473-4291-b221-b39b7ca415c9"),
                            Price = 65.00m
                        },
                        new
                        {
                            FunctionId = new Guid("57c843b9-b8b0-493c-bd99-6497aa1eec1a"),
                            FunctionDate = new DateTime(2025, 1, 25, 13, 30, 0, 0, DateTimeKind.Unspecified),
                            MovieId = new Guid("7a573bf8-d473-4291-b221-b39b7ca415c9"),
                            Price = 65.00m
                        },
                        new
                        {
                            FunctionId = new Guid("6e8b819f-76c2-402f-aaba-3fba1a79a06d"),
                            FunctionDate = new DateTime(2025, 1, 25, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            MovieId = new Guid("7a573bf8-d473-4291-b221-b39b7ca415c9"),
                            Price = 65.00m
                        },
                        new
                        {
                            FunctionId = new Guid("9a271081-4581-43b9-b97d-1419db615f43"),
                            FunctionDate = new DateTime(2025, 1, 25, 21, 45, 0, 0, DateTimeKind.Unspecified),
                            MovieId = new Guid("7a573bf8-d473-4291-b221-b39b7ca415c9"),
                            Price = 65.00m
                        });
                });

            modelBuilder.Entity("TicketEase.Service.TicketPurchase.Entities.Ticket", b =>
                {
                    b.Property<Guid>("TicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AdditionalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("FunctionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TicketId");

                    b.HasIndex("FunctionId");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            TicketId = new Guid("cfb88e29-4744-48c0-94fa-b25b92dea319"),
                            AdditionalPrice = 10.00m,
                            FunctionId = new Guid("2a943434-f25e-4233-97b8-0135de632951"),
                            UserName = "JohnDoe"
                        },
                        new
                        {
                            TicketId = new Guid("cfb88e29-4744-48c0-94fa-b25b92dea318"),
                            AdditionalPrice = 15.00m,
                            FunctionId = new Guid("44b2a7b7-f0ff-4a74-8bbf-856c19abfdb9"),
                            UserName = "JaneSmith"
                        });
                });

            modelBuilder.Entity("TicketEase.Service.TicketPurchase.Entities.Ticket", b =>
                {
                    b.HasOne("TicketEase.Service.TicketPurchase.Entities.Function", "Function")
                        .WithMany("Tickets")
                        .HasForeignKey("FunctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Function");
                });

            modelBuilder.Entity("TicketEase.Service.TicketPurchase.Entities.Function", b =>
                {
                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
